name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.lint.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.lint.txt
      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -d test_db -U github"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-test
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements.test.txt
      - name: Run tests
        run: |
          export PYTHONUNBUFFERED=1
          export FLASK_APP=main.py
          export NAA_SECRET_KEY=abcdefg_hg+k2l%!81mup%lr_jeofz9i0_pr68ubeqs3^vzs6_
          export NAA_SQLALCHEMY_ECHO=1
          export NAA_PROJECT_BASE_URL=http://api-auth.localhost:8009
          export NAA_API_V1_STR=/api/v1
          export NAA_SERVER_HOSTS=http://api-auth.localhost:8009
          export NAA_SERVER_PORT=8002
          export NAA_PROJECT_NAME=netflix-auth
          export NAA_THROTTLE_KEY_PREFIX=test_limiter:
          export NAA_THROTTLE_USER_REGISTRATION_LIMITS=59/second
          export NAA_AUTH0_DOMAIN=dev-lfllyc48.eu.auth0.com
          export NAA_AUTH0_API_AUDIENCE=https://netflix-auth.com
          export NAA_AUTH0_ISSUER=https://dev-lfllyc48.eu.auth0.com/
          export NAA_SOCIAL_GOOGLE_CLIENT_ID=secret
          export NAA_SOCIAL_GOOGLE_CLIENT_SECRET=secret
          export NAA_SOCIAL_GOOGLE_METADATA_URL=https://accounts.google.com/.well-known/openid-configuration
          export NAA_SOCIAL_YANDEX_CLIENT_ID=secret
          export NAA_SOCIAL_YANDEX_CLIENT_SECRET=secret
          export NAA_SOCIAL_YANDEX_ACCESS_TOKEN_URL=https://oauth.yandex.ru/token
          export NAA_SOCIAL_YANDEX_USERINFO_ENDPOINT=https://login.yandex.ru/info
          export NAA_SOCIAL_YANDEX_AUTHORIZE_URL=https://oauth.yandex.ru/authorize
          export NAA_SOCIAL_USE_STUBS=1
          export NAA_DEBUG=1
          export NAA_DB_HOST=db
          export NAA_DB_PORT=5432
          export NAA_DB_NAME=test_db
          export NAA_DB_USER=github
          export NAA_DB_PASSWORD=ci_pass
          export NAA_REDIS_HOST=redis
          export NAA_REDIS_PORT=6379
          export NAA_REDIS_THROTTLE_STORAGE_DB=2
          export NAA_REDIS_DEFAULT_CHARSET=utf-8
          export NAA_REDIS_DECODE_RESPONSES=1
          export NAA_REDIS_RETRY_ON_TIMEOUT=1
          export PYTEST_ADDOPTS="--ignore-glob=tests/functional/*"
          make test

  build-and-push-image:
    needs: [ lint, test ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            dockerfile: ./dev.Dockerfile
            image: yandexmiddleteamv1/netflix-auth-api
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
